import type { GoalWithTree } from "./types";
import { calcGoalProgress, formatDisplayDate } from "./utils";
import { formatMacrosLine } from "./health";

/** Build a printable HTML document for a goal (user can Save as PDF). */
export function buildGoalPrintHtml(goal: GoalWithTree, userName?: string): string {
  const progress = calcGoalProgress(goal);
  const health = goal.health_plan;
  const milestones = goal.milestones
    .map(
      (m, i) => `
      <section class="ms">
        <h3>M${i + 1}. ${escapeHtml(m.title)}</h3>
        <p class="meta">Target ${escapeHtml(formatDisplayDate(m.target_date))} · ${
        m.daily_tasks.filter((t) => t.completed).length
      }/${m.daily_tasks.length} tasks</p>
        <ul>
          ${m.daily_tasks
            .map(
              (t) =>
                `<li>${t.completed ? "✓" : "○"} ${escapeHtml(t.title)} <span class="meta">(${escapeHtml(t.scheduled_date)})</span></li>`
            )
            .join("")}
        </ul>
      </section>`
    )
    .join("");

  const healthBlock = health
    ? `
    <div class="health">
      <h2>Nutrition & movement (estimates)</h2>
      <p><strong>${health.daily_calories} kcal/day</strong> · ${escapeHtml(formatMacrosLine(health.macros))}</p>
      <p>Water: <strong>${health.water_liters} L</strong> (~${health.water_glasses} glasses)</p>
      <p>Pace: ~${health.weekly_loss_kg} kg/week · BMI ${health.bmi_current} → ${health.bmi_goal}</p>
      <h3>Home / movement</h3>
      <ul>${health.home_workouts.map((w) => `<li>${escapeHtml(w)}</li>`).join("")}</ul>
      <p class="disclaimer">${escapeHtml(health.disclaimer)}</p>
    </div>`
    : "";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Goal Garden — ${escapeHtml(goal.title)}</title>
  <style>
    body { font-family: Georgia, 'Times New Roman', serif; color: #0f172a; max-width: 720px; margin: 40px auto; padding: 0 24px; line-height: 1.5; }
    h1 { font-size: 28px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 28px; color: #065f46; }
    h3 { font-size: 15px; margin: 16px 0 4px; }
    .brand { color: #059669; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; }
    .meta { color: #64748b; font-size: 13px; }
    .badge { display: inline-block; background: #ecfdf5; color: #065f46; padding: 4px 10px; border-radius: 999px; font-size: 13px; }
    .health { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; margin-top: 20px; }
    .disclaimer { font-size: 11px; color: #94a3b8; }
    ul { padding-left: 1.2em; }
    li { margin: 4px 0; }
    .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <p class="brand">Goal Garden · Personal plan</p>
  <h1>${escapeHtml(goal.title)}</h1>
  <p class="meta">${userName ? escapeHtml(userName) + " · " : ""}Deadline ${escapeHtml(formatDisplayDate(goal.deadline))} · Progress ${progress}%</p>
  <p><span class="badge">${progress}% grown</span></p>
  ${goal.description ? `<p>${escapeHtml(goal.description)}</p>` : ""}
  ${goal.success_metrics ? `<p class="meta">Success: ${escapeHtml(goal.success_metrics)}</p>` : ""}
  ${healthBlock}
  <h2>Milestones & micro-tasks</h2>
  ${milestones}
  <div class="footer">Generated by Goal Garden · Educational guidance only · Not medical advice</div>
  <script>window.onload = function(){ setTimeout(function(){ window.print(); }, 300); }</script>
</body>
</html>`;
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function openPrintPlan(goal: GoalWithTree, userName?: string) {
  const html = buildGoalPrintHtml(goal, userName);
  const w = window.open("", "_blank");
  if (!w) {
    alert("Allow pop-ups to export your plan as PDF.");
    return;
  }
  w.document.write(html);
  w.document.close();
}

export type ShareCardData = {
  title: string;
  progress: number;
  stage: string;
  tasksDone: number;
  tasksTotal: number;
  streak: number;
  waterLine?: string;
  weekLabel: string;
};

const STAGES = [
  "Sapling",
  "Sprout",
  "Young tree",
  "Branching",
  "Leafy canopy",
  "Fruiting tree",
];

export function stageName(progress: number) {
  if (progress <= 0) return STAGES[0];
  if (progress < 20) return STAGES[1];
  if (progress < 40) return STAGES[2];
  if (progress < 60) return STAGES[3];
  if (progress < 85) return STAGES[4];
  return STAGES[5];
}

/** Draw a premium share card to canvas and download PNG */
export async function downloadShareCard(data: ShareCardData) {
  const w = 1080;
  const h = 1350;
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  // background
  const grad = ctx.createLinearGradient(0, 0, w, h);
  grad.addColorStop(0, "#0b1220");
  grad.addColorStop(0.45, "#0f1f1a");
  grad.addColorStop(1, "#0a1628");
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, w, h);

  // soft glow
  const glow = ctx.createRadialGradient(w * 0.5, h * 0.35, 40, w * 0.5, h * 0.35, 420);
  glow.addColorStop(0, "rgba(52,211,153,0.28)");
  glow.addColorStop(1, "rgba(52,211,153,0)");
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, w, h);

  // brand
  ctx.fillStyle = "#34d399";
  ctx.font = "600 28px system-ui, sans-serif";
  ctx.fillText("GOAL GARDEN", 80, 100);

  ctx.fillStyle = "#e8eef7";
  ctx.font = "700 56px system-ui, sans-serif";
  wrapText(ctx, data.title, 80, 200, w - 160, 64);

  ctx.fillStyle = "#8b9bb4";
  ctx.font = "400 28px system-ui, sans-serif";
  ctx.fillText(data.weekLabel, 80, 360);

  // big progress
  ctx.fillStyle = "#34d399";
  ctx.font = "800 140px system-ui, sans-serif";
  ctx.fillText(`${data.progress}%`, 80, 560);

  ctx.fillStyle = "#a7f3d0";
  ctx.font = "600 36px system-ui, sans-serif";
  ctx.fillText(data.stage, 80, 620);

  // stats row
  const stats = [
    { label: "Tasks", value: `${data.tasksDone}/${data.tasksTotal}` },
    { label: "Streak", value: `${data.streak}d` },
    { label: "Water", value: data.waterLine || "—" },
  ];
  stats.forEach((s, i) => {
    const x = 80 + i * 320;
    ctx.fillStyle = "rgba(255,255,255,0.06)";
    roundRect(ctx, x, 720, 280, 140, 24);
    ctx.fill();
    ctx.fillStyle = "#8b9bb4";
    ctx.font = "500 22px system-ui, sans-serif";
    ctx.fillText(s.label, x + 24, 770);
    ctx.fillStyle = "#e8eef7";
    ctx.font = "700 40px system-ui, sans-serif";
    ctx.fillText(s.value, x + 24, 830);
  });

  // tree emoji-ish simple silhouette
  ctx.fillStyle = "#166534";
  ctx.beginPath();
  ctx.ellipse(w / 2, 1120, 120, 28, 0, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = "#8b5e3c";
  ctx.fillRect(w / 2 - 16, 980, 32, 140);
  ctx.fillStyle = "#10b981";
  ctx.beginPath();
  ctx.arc(w / 2, 960, 70 + data.progress / 4, 0, Math.PI * 2);
  ctx.fill();

  ctx.fillStyle = "#64748b";
  ctx.font = "400 22px system-ui, sans-serif";
  ctx.fillText("Progress over perfection · goal.garden", 80, 1280);

  const blob = await new Promise<Blob | null>((res) =>
    canvas.toBlob((b) => res(b), "image/png")
  );
  if (!blob) return;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `goal-garden-${data.progress}pct.png`;
  a.click();
  URL.revokeObjectURL(url);
}

function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number
) {
  const words = text.split(" ");
  let line = "";
  let yy = y;
  for (const word of words) {
    const test = line + word + " ";
    if (ctx.measureText(test).width > maxWidth && line) {
      ctx.fillText(line.trim(), x, yy);
      line = word + " ";
      yy += lineHeight;
    } else {
      line = test;
    }
  }
  ctx.fillText(line.trim(), x, yy);
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}
